namespace BioStack.ProtocolOperationsExportBundleVerifierCli.Tests;

using System.Text;
using System.Text.Json;
using BioStack.ProtocolOperationsExportBundleVerifierCli;
using BioStack.Tests.Shared;
using Xunit;

/// <summary>
/// Air-gapped auditor drill capstone. This is the "hand it to a skeptical third party" guard: it
/// proves the Protocol Operations offline verification kit hangs together as a coherent, deterministic,
/// non-authority package. It ties the individual lane guards into a single readiness check that a
/// reviewer can run from a clean checkout.
///
/// The capstone is inventory- and consistency-oriented and test-owned only. It adds no product
/// surface, no API route, no frontend, no PDF generation, no persistence/database behavior, no
/// runtime behavior, and no billing/marketing claims.
///
/// Boundary note on scanning: forbidden authority-claim regexes are only applied to machine-output
/// surfaces (CLI help, human summary, receipt JSON, result JSON), which are generated by the verifier
/// and free of authority claims by construction. Human-readable posture prose (runbook, README,
/// checklist, smoke scripts) legitimately *mentions* forbidden concepts while negating them
/// ("not a provider approval workflow"), so those surfaces are checked for required non-authority
/// affirmations instead of for the absence of bare terms.
/// </summary>
public sealed class ProtocolOperationsExportBundleOfflineKitAirGappedAuditorDrillCapstoneTests
{
    private const string CliDir = "backend/tools/BioStack.ProtocolOperationsExportBundleVerifierCli";
    private const string FixtureFileName = "ProtocolOperationsExportBundle.golden.json";

    private static readonly string[] RequiredKitComponentIds =
    [
        "boundary-language-expectations",
        "cli-help-usage",
        "cli-result-json",
        "dependency-boundary-guard",
        "docs-drilldown",
        "export-bundle-contract",
        "install-runbook",
        "release-checklist",
        "result-code-catalog",
        "smoke-scripts",
        "verification-receipt-contract",
        "verifier-cli",
    ];

    [Fact]
    public void InventoryManifest_IncludesAllRequiredOfflineKitComponents()
    {
        using var manifest = JsonDocument.Parse(File.ReadAllText(RepoPath(
            "backend", "tests", "Fixtures", "ProtocolOperationsExportBundle",
            "ProtocolOperationsOfflineKitInventoryManifest.golden.json")));

        var components = manifest.RootElement.GetProperty("components").EnumerateArray().ToArray();
        var ids = components.Select(c => c.GetProperty("id").GetString()).ToArray();

        foreach (var required in RequiredKitComponentIds)
        {
            Assert.Contains(required, ids);
        }

        // Every required component must resolve to a real file in the checkout.
        foreach (var component in components)
        {
            if (!component.GetProperty("required").GetBoolean())
            {
                continue;
            }

            var location = component.GetProperty("expectedLocation").GetString()!;
            Assert.True(
                File.Exists(RepoPath(location.Split('/'))),
                $"Required kit component '{component.GetProperty("id").GetString()}' does not resolve to '{location}'.");
        }
    }

    [Fact]
    public void Runbook_ReferencesSupportedCliOperations()
    {
        var runbook = File.ReadAllText(RepoPath(CliDir.Split('/').Append("OFFLINE_VERIFICATION_RUNBOOK.md").ToArray()));

        Assert.Contains("--result-json", runbook, StringComparison.Ordinal);
        Assert.Contains("--receipt-json", runbook, StringComparison.Ordinal);
        Assert.Contains("--verify-receipt-json", runbook, StringComparison.Ordinal);
        Assert.Contains(CliDir, runbook, StringComparison.Ordinal);
    }

    [Fact]
    public void SmokeScripts_ReferenceTheSameCliOperations()
    {
        foreach (var scriptName in new[] { "smoke-offline-kit.ps1", "smoke-offline-kit.sh" })
        {
            var script = File.ReadAllText(RepoPath(CliDir.Split('/').Append(scriptName).ToArray()));

            Assert.Contains("--receipt-json", script, StringComparison.Ordinal);
            Assert.Contains("--verify-receipt-json", script, StringComparison.Ordinal);
            Assert.Contains("--result-json", script, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void ResultCodeCatalog_CoversAllNegativeFixtureFamilies()
    {
        using var catalog = JsonDocument.Parse(File.ReadAllText(RepoPath(
            "backend", "tests", "Fixtures", "ProtocolOperationsExportBundle",
            "ProtocolOperationsOfflineVerificationResultCodeCatalog.golden.json")));

        var entries = catalog.RootElement.GetProperty("entries").EnumerateArray().ToArray();
        var codes = entries.Select(e => e.GetProperty("code").GetString()!).ToArray();

        foreach (var family in new[] { "POBUNDLE_", "PORECEIPT_", "POCLI_", "POBOUNDARY_" })
        {
            Assert.Contains(codes, code => code.StartsWith(family, StringComparison.Ordinal));
        }

        var boundaryCategories = entries
            .Select(e => e.GetProperty("boundaryPostureCategory").GetString())
            .Where(value => value is not null)
            .ToArray();

        foreach (var category in new[] { "medical-language", "pdf-claim", "persistence-claim", "runtime-claim" })
        {
            Assert.Contains(category, boundaryCategories);
        }
    }

    [Fact]
    public void CliResultJsonSnapshot_RemainsPresentAndParseable()
    {
        var snapshotPath = RepoPath(
            "backend", "tests", "Fixtures", "ProtocolOperationsExportBundle",
            "ProtocolOperationsResultJsonSchemaSnapshot.golden.json");

        Assert.True(File.Exists(snapshotPath), $"Missing CLI result JSON schema snapshot at '{snapshotPath}'.");

        var raw = File.ReadAllText(snapshotPath);
        Assert.False(string.IsNullOrWhiteSpace(raw));
        using var _ = JsonDocument.Parse(raw); // stability is enforced by the dedicated snapshot test.
    }

    [Fact]
    public void RedactionAndAirGapGuards_ArePresent()
    {
        var guardFiles = new[]
        {
            RepoPath("backend", "tests", "BioStack.ProtocolOperationsExportBundleVerifierCli.Tests",
                "ProtocolOperationsOfflineKitRedactionPrivacyTests.cs"),
            RepoPath("backend", "tests", "BioStack.ProtocolOperationsExportBundleVerifierCli.Tests",
                "ProtocolOperationsExportBundleVerifierCliAirGapBoundaryTests.cs"),
            RepoPath("backend", "tests", "BioStack.Application.Tests",
                "ProtocolOperationsOfflineVerificationAirGapBoundaryTests.cs"),
        };

        foreach (var file in guardFiles)
        {
            Assert.True(File.Exists(file), $"Missing offline-kit guard '{file}'.");
        }
    }

    [Fact]
    public void ReleaseChecklist_IncludesRequiredValidationCommands()
    {
        var checklist = File.ReadAllText(RepoPath(
            CliDir.Split('/').Append("OFFLINE_VERIFICATION_RELEASE_CHECKLIST.md").ToArray()));

        var requiredCommands = new[]
        {
            "dotnet build backend/BioStack.sln",
            "--filter ProtocolOperationsExportBundle",
            "--filter ProtocolOperationsExportBundleGoldenFixture",
            "--filter ProtocolIntelligenceOfflineBoundaryTests",
            "dotnet test backend/tests/BioStack.ProtocolOperationsExportBundleVerifierCli.Tests",
            "dotnet list backend/BioStack.sln package --include-transitive --vulnerable",
            "git diff --check",
        };

        foreach (var command in requiredCommands)
        {
            Assert.Contains(command, checklist, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void KitDocs_PreserveNonAuthorityPosture()
    {
        // Runbook affirms explicit non-authority posture and non-goals.
        var runbook = File.ReadAllText(RepoPath(CliDir.Split('/').Append("OFFLINE_VERIFICATION_RUNBOOK.md").ToArray()));
        var runbookRequired = new[]
        {
            "educational",
            "observational",
            "mathematical logic only",
            "medical validation tool",
            "database-state verifier",
            "runtime execution verifier",
            "provider approval workflow",
            "PDF generator",
        };
        Assert.Empty(OfflineVerificationBoundaryLanguageCorpus.FindMissingRequiredConcepts(runbook, runbookRequired));

        // CLI docs drilldown (README) affirms the shared required posture concepts.
        var readme = File.ReadAllText(RepoPath(CliDir.Split('/').Append("README.md").ToArray()));
        Assert.Empty(OfflineVerificationBoundaryLanguageCorpus.FindMissingRequiredConcepts(
            readme, OfflineVerificationBoundaryLanguageCorpus.DocsDrilldownRequiredConcepts));

        // Root repository README preserves the educational/observational safety posture.
        var rootReadme = File.ReadAllText(RepoPath("README.md"));
        Assert.Contains("BioStack is for educational and observational use only.", rootReadme, StringComparison.Ordinal);
        Assert.Contains("Mathematical Logic Only", rootReadme, StringComparison.Ordinal);
    }

    [Fact]
    public void MachineOutputSurfaces_CarryNoForbiddenAuthorityConcepts()
    {
        var bundleJson = ReadFixtureJson();
        var bundlePath = CreateTempJsonFile(bundleJson);
        var receiptPath = CreateTempJsonFile(EmitReceiptJson(bundlePath));

        var surfaces = new[]
        {
            InvokeCli("--help").StandardOutput,
            InvokeCli(bundlePath).StandardOutput,
            InvokeCli("--result-json", bundlePath).StandardOutput,
            InvokeCli("--receipt-json", bundlePath).StandardOutput,
            InvokeCli("--verify-receipt-json", receiptPath).StandardOutput,
            InvokeCli("--result-json", "--verify-receipt-json", receiptPath).StandardOutput,
        };

        foreach (var surface in surfaces)
        {
            Assert.Empty(OfflineVerificationBoundaryLanguageCorpus.FindForbiddenAuthorityConcepts(surface));
        }
    }

    private static string EmitReceiptJson(string bundlePath)
    {
        var result = InvokeCli("--receipt-json", bundlePath);
        Assert.Equal(0, result.ExitCode);
        return result.StandardOutput;
    }

    private static (int ExitCode, string StandardOutput, string StandardError) InvokeCli(params string[] args)
    {
        using var stdout = new StringWriter();
        using var stderr = new StringWriter();
        var exitCode = ProtocolOperationsExportBundleVerifierCli.Run(args, stdout, stderr);
        return (exitCode, stdout.ToString(), stderr.ToString());
    }

    private static string CreateTempJsonFile(string json)
    {
        var path = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.json");
        File.WriteAllText(path, json, Encoding.UTF8);
        return path;
    }

    private static string ReadFixtureJson()
    {
        return File.ReadAllText(Path.Combine(
            AppContext.BaseDirectory, "Fixtures", "ProtocolOperationsExportBundle", FixtureFileName));
    }

    private static string RepoPath(params string[] segments)
    {
        return Path.Combine(new[] { OfflineVerificationBoundaryLanguageCorpus.RepositoryRoot() }.Concat(segments).ToArray());
    }
}
