namespace BioStack.ProtocolOperationsExportBundleVerifierCli.Tests;

using System.Text;
using BioStack.ProtocolOperationsExportBundleVerifierCli;
using BioStack.Tests.Shared;
using Xunit;

/// <summary>
/// Applies the shared offline-verification boundary-language corpus to the CLI machine-output
/// surfaces: CLI help/usage text, the human-readable bundle summary, receipt JSON, and result JSON
/// for both bundle and receipt verification. These surfaces are generated by the verifier and must
/// never carry forbidden authority claims.
/// </summary>
public sealed class ProtocolOperationsExportBundleVerifierCliBoundaryLanguageCorpusTests
{
    private const string FixtureFileName = "ProtocolOperationsExportBundle.golden.json";

    [Fact]
    public void CliHelpText_ContainsNoForbiddenAuthorityConcepts()
    {
        var result = InvokeCli("--help");

        AssertNoForbiddenAuthorityConcepts(result.StandardOutput);
    }

    [Fact]
    public void CliBundleSummary_ContainsNoForbiddenAuthorityConcepts()
    {
        var bundlePath = CreateTempJsonFile(ReadFixtureJson());
        var result = InvokeCli(bundlePath);

        Assert.Equal(0, result.ExitCode);
        AssertNoForbiddenAuthorityConcepts(result.StandardOutput);
    }

    [Fact]
    public void ReceiptJson_ContainsNoForbiddenAuthorityConcepts()
    {
        var bundlePath = CreateTempJsonFile(ReadFixtureJson());
        var result = InvokeCli("--receipt-json", bundlePath);

        Assert.Equal(0, result.ExitCode);
        AssertNoForbiddenAuthorityConcepts(result.StandardOutput);
    }

    [Fact]
    public void ResultJson_ForBundleVerification_ContainsNoForbiddenAuthorityConcepts()
    {
        var bundlePath = CreateTempJsonFile(ReadFixtureJson());
        var result = InvokeCli("--result-json", bundlePath);

        Assert.Equal(0, result.ExitCode);
        AssertNoForbiddenAuthorityConcepts(result.StandardOutput);
    }

    [Fact]
    public void ResultJson_ForReceiptVerification_ContainsNoForbiddenAuthorityConcepts()
    {
        var receiptPath = CreateTempJsonFile(EmitReceiptJson());
        var result = InvokeCli("--result-json", "--verify-receipt-json", receiptPath);

        Assert.Equal(0, result.ExitCode);
        AssertNoForbiddenAuthorityConcepts(result.StandardOutput);
    }

    private static void AssertNoForbiddenAuthorityConcepts(string text)
    {
        var found = OfflineVerificationBoundaryLanguageCorpus.FindForbiddenAuthorityConcepts(text);
        Assert.Empty(found);
    }

    private static string EmitReceiptJson()
    {
        var bundlePath = CreateTempJsonFile(ReadFixtureJson());
        var result = InvokeCli("--receipt-json", bundlePath);

        Assert.Equal(0, result.ExitCode);
        return result.StandardOutput;
    }

    private static (int ExitCode, string StandardOutput, string StandardError) InvokeCli(params string[] args)
    {
        using var stdout = new StringWriter();
        using var stderr = new StringWriter();
        var exitCode = ProtocolOperationsExportBundleVerifierCli.Run(args, stdout, stderr);
        return (exitCode, stdout.ToString(), stderr.ToString());
    }

    private static string CreateTempJsonFile(string json)
    {
        var path = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.json");
        File.WriteAllText(path, json, Encoding.UTF8);
        return path;
    }

    private static string ReadFixtureJson()
    {
        var fixturePath = Path.Combine(
            AppContext.BaseDirectory,
            "Fixtures",
            "ProtocolOperationsExportBundle",
            FixtureFileName);

        return File.ReadAllText(fixturePath);
    }
}
