// <auto-generated />
using System;
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BioStack.Infrastructure.Migrations
{
    [DbContext(typeof(BioStackDbContext))]
    partial class BioStackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BioStack.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("StripeCustomerId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AuthChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RedirectPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AuthChallenges");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Type", "ValueNormalized")
                        .IsUnique();

                    b.ToTable("AuthIdentities");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.CheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Appetite")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DigestiveHealth")
                        .HasColumnType("integer");

                    b.Property<int?>("Endurance")
                        .HasColumnType("integer");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<int?>("Eyesight")
                        .HasColumnType("integer");

                    b.Property<int?>("Focus")
                        .HasColumnType("integer");

                    b.Property<string>("GiSymptoms")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("JointPain")
                        .HasColumnType("integer");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProtocolRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Recovery")
                        .HasColumnType("integer");

                    b.Property<string>("SideEffects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SkinQuality")
                        .HasColumnType("integer");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("integer");

                    b.Property<int?>("Strength")
                        .HasColumnType("integer");

                    b.Property<int?>("ThoughtClarity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProtocolRunId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.CompoundInteractionHint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompoundA")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompoundB")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InteractionType")
                        .HasColumnType("integer");

                    b.Property<string>("MechanismOverlap")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Strength")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompoundA", "CompoundB")
                        .IsUnique();

                    b.ToTable("CompoundInteractionHints");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.CompoundRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PricePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("CompoundRecords");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.InteractionFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompoundNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EvidenceConfidence")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OverlapType")
                        .HasColumnType("integer");

                    b.Property<string>("PathwayTag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("InteractionFlags");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.KnowledgeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvoidWith")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("CompatibleBlends")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugInteractions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvidenceTier")
                        .HasColumnType("integer");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IncrementalEscalationSteps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaxReportedDose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MechanismSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptimizationCarbs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptimizationExercise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptimizationProtein")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptimizationSleep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptimizationSupplements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PairsWellWith")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pathways")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredTimeOfDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedDosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegulatoryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceReferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandardDosageRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieredDosing")
                        .HasColumnType("text");

                    b.Property<string>("VialCompatibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeeklyDosageSchedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeEntries");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.LeadCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Source")
                        .IsUnique();

                    b.ToTable("LeadCaptures");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.PersonProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoalSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PersonProfiles");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Protocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvolutionContext")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("EvolvedFromRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OriginProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("EvolvedFromRunId");

                    b.HasIndex("OriginProtocolId");

                    b.HasIndex("ParentProtocolId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId", "OriginProtocolId", "Version");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolComputationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InputSnapshot")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OutputResult")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProtocolRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("ProtocolRunId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("ProtocolComputationRecords");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CalculatorResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompoundCategorySnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompoundEndDateSnapshot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompoundGoalSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompoundNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CompoundNotesSnapshot")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("CompoundPricePaidSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CompoundRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompoundSourceSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CompoundStartDateSnapshot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompoundStatusSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompoundRecordId");

                    b.HasIndex("ProtocolId");

                    b.ToTable("ProtocolItems");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ProtocolPhases");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolReviewCompletedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProtocolRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("ProtocolRunId");

                    b.ToTable("ProtocolReviewCompletedEvents");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("PersonId", "Status");

                    b.ToTable("ProtocolRuns");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.StripeWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique();

                    b.ToTable("StripeWebhookEvents");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CurrentPeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StripeCustomerId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("PersonId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AuthChallenge", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.AuthIdentity", "Identity")
                        .WithMany("Challenges")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AuthIdentity", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.AppUser", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("CheckIns")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioStack.Domain.Entities.ProtocolRun", "ProtocolRun")
                        .WithMany("CheckIns")
                        .HasForeignKey("ProtocolRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PersonProfile");

                    b.Navigation("ProtocolRun");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.CompoundRecord", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("Compounds")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonProfile");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.PersonProfile", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.AppUser", "Owner")
                        .WithMany("Profiles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Protocol", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.ProtocolRun", "EvolvedFromRun")
                        .WithMany()
                        .HasForeignKey("EvolvedFromRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BioStack.Domain.Entities.Protocol", "OriginProtocol")
                        .WithMany()
                        .HasForeignKey("OriginProtocolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BioStack.Domain.Entities.Protocol", "ParentProtocol")
                        .WithMany("ChildVersions")
                        .HasForeignKey("ParentProtocolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("Protocols")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvolvedFromRun");

                    b.Navigation("OriginProtocol");

                    b.Navigation("ParentProtocol");

                    b.Navigation("PersonProfile");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolComputationRecord", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.Protocol", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioStack.Domain.Entities.ProtocolRun", "ProtocolRun")
                        .WithMany()
                        .HasForeignKey("ProtocolRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Protocol");

                    b.Navigation("ProtocolRun");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolItem", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.CompoundRecord", "CompoundRecord")
                        .WithMany()
                        .HasForeignKey("CompoundRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioStack.Domain.Entities.Protocol", "Protocol")
                        .WithMany("Items")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompoundRecord");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolPhase", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("ProtocolPhases")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonProfile");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolReviewCompletedEvent", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.Protocol", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioStack.Domain.Entities.ProtocolRun", "ProtocolRun")
                        .WithMany()
                        .HasForeignKey("ProtocolRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Protocol");

                    b.Navigation("ProtocolRun");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolRun", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("ProtocolRuns")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioStack.Domain.Entities.Protocol", "Protocol")
                        .WithMany("Runs")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonProfile");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Session", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.AppUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("BioStack.Domain.Entities.PersonProfile", "PersonProfile")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonProfile");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("Profiles");

                    b.Navigation("Sessions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.AuthIdentity", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.PersonProfile", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Compounds");

                    b.Navigation("ProtocolPhases");

                    b.Navigation("ProtocolRuns");

                    b.Navigation("Protocols");

                    b.Navigation("TimelineEvents");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.Protocol", b =>
                {
                    b.Navigation("ChildVersions");

                    b.Navigation("Items");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProtocolRun", b =>
                {
                    b.Navigation("CheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
