'use client';

import {
  formatAnalyzerEntry,
  type AnalyzerDraftCompoundImport,
  type AnalyzerProtocolDraft,
} from '@/lib/analyzerStorage';
import { formatDate } from '@/lib/utils';

export type AnalyzerDraftReviewTarget =
  | { kind: 'profile'; profileName: string }
  | { kind: 'new-profile' }
  | { kind: 'choose-profile' };

interface AnalyzerDraftReviewPanelProps {
  draft: AnalyzerProtocolDraft;
  /** User-entered compounds that would actually be added (already deduplicated against the target). */
  imports: AnalyzerDraftCompoundImport[];
  target: AnalyzerDraftReviewTarget;
  onConfirm?: () => void;
  onDismiss?: () => void;
  /** new-profile only: whether the compounds should be added when the profile is created. */
  includeOnCreate?: boolean;
  onIncludeOnCreateChange?: (include: boolean) => void;
  isSubmitting?: boolean;
  error?: string | null;
}

export function AnalyzerDraftReviewPanel({
  draft,
  imports,
  target,
  onConfirm,
  onDismiss,
  includeOnCreate = true,
  onIncludeOnCreateChange,
  isSubmitting = false,
  error = null,
}: AnalyzerDraftReviewPanelProps) {
  const importNames = new Set(imports.map((item) => item.name.toLowerCase()));
  const importCount = imports.length;
  const compoundWord = importCount === 1 ? 'compound' : 'compounds';
  const savedOn = safeFormatDate(draft.createdAt);

  return (
    <section
      aria-labelledby="analyzer-draft-review-title"
      className="rounded-lg border border-emerald-300/15 bg-emerald-500/[0.06] p-5"
      data-testid="analyzer-draft-review"
    >
      <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-200/75">Recovered from this browser</p>
      <h2 id="analyzer-draft-review-title" className="mt-2 text-xl font-semibold text-white">
        Your analyzed protocol is waiting.
      </h2>
      <p className="mt-2 text-sm leading-6 text-white/58">
        Saved from the Protocol Analyzer{draft.goal ? ` for ${draft.goal}` : ''}
        {savedOn ? ` on ${savedOn}` : ''}. Review what you entered before anything is added — nothing has been applied yet.
      </p>

      <div className="mt-4">
        <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-white/40">As you entered it</p>
        <ul className="mt-2 space-y-1.5" data-testid="analyzer-draft-original">
          {draft.protocol.map((entry, index) => {
            const asEntered = formatAnalyzerEntry(entry);
            const skipped = !importNames.has(entry.compoundName.toLowerCase());
            return (
              <li
                key={`${entry.compoundName}-${index}`}
                className="flex flex-wrap items-baseline justify-between gap-x-4 rounded-md border border-white/8 bg-black/20 px-3 py-2 text-sm"
              >
                <span className="font-medium text-white/85">{entry.compoundName}</span>
                <span className="text-white/50">
                  {asEntered || 'no amount entered'}
                  {skipped ? ' · already on this profile' : ''}
                </span>
              </li>
            );
          })}
        </ul>
      </div>

      {draft.optimizedProtocol.length > 0 && (
        <details className="mt-4 rounded-md border border-white/8 bg-black/10 px-3 py-2" data-testid="analyzer-draft-alternative">
          <summary className="cursor-pointer text-sm font-medium text-white/70">
            Analyzer alternative — comparison only, not applied
          </summary>
          <p className="mt-2 text-xs leading-5 text-white/45">
            Generated by the analyzer for comparison only. BioStack records what you entered and does not change it. If you decide to change your stack, add compounds yourself.
          </p>
          <ul className="mt-2 space-y-1">
            {draft.optimizedProtocol.map((entry, index) => (
              <li key={`${entry.compoundName}-${index}`} className="flex flex-wrap justify-between gap-x-4 text-sm text-white/55">
                <span>{entry.compoundName}</span>
                <span>{formatAnalyzerEntry(entry) || 'no amount listed'}</span>
              </li>
            ))}
          </ul>
        </details>
      )}

      {target.kind === 'new-profile' && onIncludeOnCreateChange && (
        <label className="mt-4 flex items-start gap-3 text-sm text-white/75">
          <input
            type="checkbox"
            className="mt-1"
            checked={includeOnCreate}
            disabled={isSubmitting}
            onChange={(event) => onIncludeOnCreateChange?.(event.target.checked)}
          />
          <span>
            Add these {importCount} {compoundWord} to the new profile as Active compounds, keeping what you entered as a note.
          </span>
        </label>
      )}

      {target.kind === 'profile' && importCount === 0 && (
        <p className="mt-4 text-sm leading-6 text-white/58">
          Everything you entered is already on {target.profileName}. Nothing to add.
        </p>
      )}

      {target.kind === 'choose-profile' && (
        <p className="mt-4 text-sm leading-6 text-white/58">
          Choose a profile above to review adding these compounds, or create a new profile.
        </p>
      )}

      {error && (
        <p role="alert" className="mt-4 rounded-md border border-red-300/20 bg-red-500/10 px-3 py-2 text-sm text-red-100/80">
          {error}
        </p>
      )}

      <div className="mt-5 flex flex-wrap gap-3">
        {target.kind === 'profile' && onConfirm && importCount > 0 && (
          <button
            type="button"
            onClick={onConfirm}
            disabled={isSubmitting}
            className="rounded-lg bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950 transition-colors hover:bg-emerald-300 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isSubmitting ? 'Adding…' : `Add ${importCount} ${compoundWord} to ${target.profileName}`}
          </button>
        )}
        {target.kind === 'new-profile' && onConfirm && (
          <button
            type="button"
            onClick={onConfirm}
            className="rounded-lg bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950 transition-colors hover:bg-emerald-300"
          >
            Continue Profile Setup
          </button>
        )}
        {target.kind === 'choose-profile' && onConfirm && (
          <button
            type="button"
            onClick={onConfirm}
            className="rounded-lg border border-emerald-300/30 px-5 py-3 text-sm font-semibold text-emerald-100/90 transition-colors hover:border-emerald-300/60"
          >
            Create a new profile
          </button>
        )}
        {onDismiss && (
          <button
            type="button"
            onClick={onDismiss}
            disabled={isSubmitting}
            className="rounded-lg border border-white/[0.1] px-5 py-3 text-sm font-semibold text-white/75 hover:border-white/20 disabled:opacity-60"
          >
            {target.kind === 'profile' && importCount === 0 ? 'Dismiss' : 'Not now'}
          </button>
        )}
      </div>
    </section>
  );
}

function safeFormatDate(value: string): string {
  try {
    return Number.isNaN(new Date(value).getTime()) ? '' : formatDate(value);
  } catch {
    return '';
  }
}
