// <auto-generated />
using System;
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BioStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BioStackDbContext))]
    [Migration("20260803120000_AddSpineChainCheckpoints")]
    partial class AddSpineChainCheckpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            // Intentionally partial, matching this repository's hand-written migration convention.
            modelBuilder.Entity("BioStack.Domain.Governance.SpineChainCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadEntryHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckpointedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureAlgorithm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SequenceNumber");

                    b.HasIndex("CheckpointedAtUtc");

                    b.ToTable("SpineChainCheckpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
