// <auto-generated />
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BioStack.Infrastructure.Persistence.Migrations
{
    // NOTE: The central model snapshot is intentionally minimal in this repo (migrations are
    // hand-written; dev/test build schema from the live model via EnsureCreated). This designer
    // carries only the [Migration] id so production Migrate() applies the migration in order; the
    // BuildTargetModel body is not authoritative for the full model.
    [DbContext(typeof(BioStackDbContext))]
    [Migration("20260626100000_AddCompoundGraphArtifacts")]
    partial class AddCompoundGraphArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
#pragma warning restore 612, 618
        }
    }
}
