// <auto-generated />
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BioStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BioStackDbContext))]
    [Migration("20260626000000_AddReceiptClassToSpine")]
    partial class AddReceiptClassToSpine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BioStack.Infrastructure.Persistence.Entities.StagedTranscriptCandidateReviewEntity", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Canonicality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeterministicFixture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromotedAtUtc")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromotedKnowledgeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SegmentSnapshotSignature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCanonicalName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("ReviewState");

                    b.ToTable("StagedTranscriptCandidateReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_StagedTranscriptCandidateReviews_Canonicality_NonCanonical", "Canonicality = 'non_canonical'");

                            t.HasCheckConstraint("CK_StagedTranscriptCandidateReviews_ReviewState_Lifecycle", "ReviewState IN ('pending_review','review_deferred','review_rejected','review_approved_for_promotion')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
