// <auto-generated />
using System;
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BioStackDbContext))]
    [Migration("20260511000000_AddGovernedSpine")]
    partial class AddGovernedSpine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BioStack.Domain.Governance.SpineEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceRefsJson")
                        .IsRequired()
                        .HasDefaultValue("[]")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyHashValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyHashVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ReceiptUri")
                        .IsUnique();

                    b.HasIndex("SubjectUri");

                    b.ToTable("SpineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
