// <auto-generated />
using System;
using BioStack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioStack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BioStackDbContext))]
    partial class BioStackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BioStack.Infrastructure.Persistence.Entities.StagedTranscriptCandidateReviewEntity", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Canonicality")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IsDeterministicFixture")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IntakeRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SegmentSnapshotSignature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCanonicalName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotedKnowledgeEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromotedAtUtc")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("ReviewState");

                    b.HasIndex("IntakeRequestId");

                    b.ToTable("StagedTranscriptCandidateReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_StagedTranscriptCandidateReviews_Canonicality_NonCanonical", "Canonicality = 'non_canonical'");

                            t.HasCheckConstraint("CK_StagedTranscriptCandidateReviews_ReviewState_Lifecycle", "ReviewState IN ('pending_review','review_deferred','review_rejected','review_approved_for_promotion')");
                        });
                });

            modelBuilder.Entity("BioStack.Domain.Entities.ProviderAccessRequest", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("TEXT");
                    b.Property<DateTime>("ConsentRecordedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("ConsentVersion").IsRequired().HasMaxLength(64).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("Organization").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Owner").HasMaxLength(160).HasColumnType("TEXT");
                    b.Property<string>("Role").IsRequired().HasMaxLength(120).HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAtUtc").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Status", "Owner", "CreatedAtUtc");
                    b.ToTable("ProviderAccessRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
