namespace BioStack.Tests.Shared;

using System.Text.RegularExpressions;

/// <summary>
/// Single test-owned corpus of the boundary-language rules for the Protocol Operations offline
/// verification kit. It centralizes two things so they cannot drift across artifacts, docs, the CLI,
/// result JSON, and design notes:
///
/// 1. Forbidden authority concepts — affirmative authority claims that must never appear in machine
///    output surfaces (receipt JSON, result JSON, CLI help, CLI human summary). Machine surfaces are
///    generated by the verifier and are guaranteed free of these by construction.
///
/// 2. Required posture concepts — inspection-only, non-authority language a human-readable posture
///    surface must affirm. Posture prose legitimately *mentions* forbidden concepts while negating
///    them ("does not provide medical advice"), so these surfaces are checked for required affirmations
///    rather than for the absence of bare terms.
///
/// This corpus is test-owned only. It introduces no production validation, no user-facing claim
/// expansion, and no medical or compound examples.
/// </summary>
public static class OfflineVerificationBoundaryLanguageCorpus
{
    /// <summary>Affirmative authority claims forbidden on machine-output surfaces.</summary>
    public static readonly IReadOnlyList<ForbiddenConcept> ForbiddenAuthorityConcepts =
    [
        new("dosing recommendation", @"\bdos(?:e|es|ed|ing|age)\b|\brecommend(?:ation|ations|ed|ing|s)?\b"),
        new("diagnosis", @"\bdiagnos(?:is|es|e|ed|ing|tic)\b"),
        new("treatment", @"\btreat(?:ment|ments|ed|ing|s)?\b"),
        new("prescription", @"\bprescrib(?:e|ed|ing|es)\b|\bprescription(?:s)?\b"),
        new("clinical approval", @"\bclinical(?:ly)?\s+(?:approv|appropriate|correct)"),
        new("provider approval", @"\bprovider\s+approv"),
        new("therapeutic instruction", @"\btherapeutic\s+instruction"),
        new("medical advice authority", @"\bmedical advice\b"),
        new("pdf authentication claim", @"\bauthenticat\w*\b[^.]*\bpdf\b|\bpdf\b[^.]*\bauthenticat\w*\b"),
        new("database verification claim", @"\bverif\w*\b[^.]*\bdatabase\b|\bdatabase\b[^.]*\bverif\w*\b"),
        new("runtime execution claim", @"\bprotocol intelligence\b[^.]*\bexecut\w*\b|\bexecut\w*\b[^.]*\bprotocol intelligence\b"),
        new("guaranteed health outcome", @"\bguarantee\w*\b[^.]*\b(?:health|outcome|result)\b"),
        new("certifies medical correctness", @"\bcertif\w*\b"),
    ];

    /// <summary>Posture concepts the CLI docs drilldown (README) must affirm.</summary>
    public static readonly IReadOnlyList<string> DocsDrilldownRequiredConcepts =
    [
        "observational",
        "educational",
        "inspection",
        "local artifact",
        "supplied",
        "does not prove",
        "medical advice",
        "PDF authenticity",
        "persistence/database",
        "Protocol Intelligence runtime",
        "offline",
    ];

    /// <summary>Posture concepts the release checklist must affirm.</summary>
    public static readonly IReadOnlyList<string> ReleaseChecklistRequiredConcepts =
    [
        "supplied-artifact",
        "medical advice",
        "PDF authenticity",
        "persistence/database",
        "Protocol Intelligence runtime",
        "offline",
    ];

    /// <summary>Posture concepts the export bundle disclaimer must affirm.</summary>
    public static readonly IReadOnlyList<string> BundleDisclaimerRequiredConcepts =
    [
        "observational",
        "non-medical",
        "review only",
    ];

    /// <summary>Returns the labels of every forbidden authority concept found in <paramref name="text"/>.</summary>
    public static IReadOnlyList<string> FindForbiddenAuthorityConcepts(string text)
    {
        var matches = new List<string>();
        foreach (var concept in ForbiddenAuthorityConcepts)
        {
            if (Regex.IsMatch(text, concept.Pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant))
            {
                matches.Add(concept.Label);
            }
        }

        return matches;
    }

    /// <summary>Returns the required concepts that are missing from <paramref name="text"/> (case-insensitive).</summary>
    public static IReadOnlyList<string> FindMissingRequiredConcepts(string text, IEnumerable<string> requiredConcepts)
    {
        return requiredConcepts
            .Where(concept => text.IndexOf(concept, StringComparison.OrdinalIgnoreCase) < 0)
            .ToArray();
    }

    public static string RepositoryRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "backend", "BioStack.sln")))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate BioStack repository root.");
    }

    public sealed record ForbiddenConcept(string Label, string Pattern);
}
