import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { sync, collect } from './sync-reviewed-study-design.mjs';

test('canonical empty manifest clears stale generated bytes; check never silently rewrites', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'biostack-display-sync-'));
  try {
    await mkdir(path.join(root, 'contracts'));
    await writeFile(path.join(root, 'contracts/reviewed-study-design.json'), '{"schemaVersion":"1.0.0","entries":[]}');
    await sync(root, false); await sync(root, true);
    const target = path.join(root, 'frontend/src/lib/generated/reviewed-study-design.json');
    await writeFile(target, '[{"stale":true}]');
    await assert.rejects(sync(root, true), /Stale/);
    await sync(root, false); assert.equal(await readFile(target, 'utf8'), '[]\n');
  } finally { await rm(root, { recursive: true, force: true }); }
});
test('rejects arbitrary manifest fields instead of expanding public scope', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'biostack-display-manifest-'));
  try {
    await mkdir(path.join(root, 'contracts'));
    await writeFile(path.join(root, 'contracts/reviewed-study-design.json'), '{"schemaVersion":"1.0.0","entries":[],"approved":true}');
    await assert.rejects(collect(root), /Invalid/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test('collects later relevant decisions from all issued batches, not only the named approval', async () => {
  const root = await mkdtemp(path.join(tmpdir(), 'biostack-display-decisions-'));
  try {
    await mkdir(path.join(root, 'contracts')); await mkdir(path.join(root, 'research/review-decisions'), { recursive: true });
    const write = (file, data) => writeFile(path.join(root, file), JSON.stringify(data));
    await write('contracts/reviewed-study-design.json', { schemaVersion: '1.0.0', entries: [{ packetPath: 'packet.json', claimId: 'c', sourceItemId: 's', receiptPath: 'receipt.json', payloadPath: 'payload.json', decisionId: 'first' }] });
    await write('packet.json', { recordType: 'compound-evidence-packet', compound: { canonicalName: 'Example' }, claims: [{ claimId: 'c' }], sources: [{ sourceId: 's' }] });
    await write('receipt.json', {}); await write('payload.json', { canonicalName: 'Example' });
    const batch = { batchId: 'synthetic', reviewerId: 'synthetic reviewer', reviewedAt: '2026-09-13T00:00:00Z', notes: [] };
    await write('research/review-decisions/first.json', { schemaVersion: '1.0.0', recordType: 'review-decision-batch', batch, decisions: [{ decisionId: 'first', compoundName: 'Example' }] });
    await write('research/review-decisions/later.json', { schemaVersion: '1.0.0', recordType: 'review-decision-batch', batch: { ...batch, batchId: 'later' }, decisions: [{ decisionId: 'later', compoundName: 'Example', decision: 'request-changes' }, { decisionId: 'unrelated', compoundName: 'Other' }] });
    assert.deepEqual((await collect(root)).decisions.map(d => d.decisionId), ['first', 'later']);
    await write('research/review-decisions/later.json', { schemaVersion: '99.0.0', recordType: 'review-decision-batch', decisions: [] });
    await assert.rejects(collect(root), /Unsupported/);
  } finally { await rm(root, { recursive: true, force: true }); }
});
