import { describe, expect, it } from 'vitest';

const ALL_NEW_COPY = [
  // LockedTierCard
  'See how your protocol fits together',
  "Score your active stack, surface synergies and conflicts, and run counterfactual scenarios — all included in Operator.",
  'Protocol simulation unlocks with Operator',
  "Model compound timing across phases, visualize your protocol's structure, and see how your stack is projected to play out over time.",
  // UpgradeBanner
  'Pattern memory, drift analysis, and sequence intelligence unlock with Commander',
  // Billing — Observer
  'Observer includes up to 8 active compounds. Existing data stays available if a paid plan ends.',
  // Billing — Operator card
  'Protocol scoring and analysis',
  'See how your compounds interact — score your protocol, identify synergies and conflicts, and model what changes with counterfactual scenarios. Removes the active compound limit.',
  'Full protocol analysis',
  'Current-stack relationship intelligence',
  'Weekly protocol calendar',
  'Diet and lifestyle framework',
  'Progress and milestone tracking',
  // Billing — Commander card
  'Run history and trend analysis',
  'Track how your protocols evolve — detect trends and drift, anticipate the next phase from prior runs, and get structured reviews across all your protocol runs.',
  'Protocol review across run history',
  'Pattern memory snapshots',
  'Protocol drift snapshots',
  'Sequence expectation snapshots',
  'Monitoring and lab view',
  'Cross-protocol mission control',
  // Analyzer
  'Track whether these patterns hold',
  'Add the compounds you entered to a BioStack profile and check in over time to see whether the synergies and conflicts playing out now actually hold. You review them before anything is added.',
  'Add this stack to BioStack',
  'It stays on this browser through sign-in until you review it.',
  // Sign-in continuation promise
  'Your saved analysis is waiting on this browser.',
  'Finish sign-in here, then review the compounds you entered before they are added to a profile. Nothing is applied automatically.',
  // AnalyzerDraftReviewPanel (post-sign-in draft recovery)
  'Your analyzed protocol is waiting.',
  'Review what you entered before anything is added — nothing has been applied yet.',
  'Analyzer alternative — comparison only, not applied',
  'Generated by the analyzer for comparison only. BioStack records what you entered and does not change it. If you decide to change your stack, add compounds yourself.',
  'Add these compounds to the new profile as Active compounds, keeping what you entered as a note.',
  'Choose a profile above to review adding these compounds, or create a new profile.',
  // Analyzer draft compound notes
  'Added from your Protocol Analyzer entry (as entered: 500 mcg · daily · 4 weeks). Recorded exactly as you wrote it.',
  'We added the compounds you entered in the Protocol Analyzer, as you entered them. Review them below.',
  // InteractionIntelligenceCard CTA
  'Tracking this protocol over time will show whether these interaction patterns hold.',
  'Start tracking',
];

const BANNED = [
  'you should',
  'dosage',
  'diagnosis',
  'recommend',
  ' take ',
  'medical advice',
  'clinical guidance',
  'dose',
];

describe('conversion copy safety', () => {
  it('contains no banned medical or recommendation language', () => {
    for (const line of ALL_NEW_COPY) {
      for (const phrase of BANNED) {
        expect(line.toLowerCase(), `"${line}" contains banned phrase "${phrase}"`).not.toContain(phrase.toLowerCase());
      }
    }
  });

  it('free-tier compound limit references 8 not 5 in copy that mentions compounds', () => {
    const limitLines = ALL_NEW_COPY.filter((l) => /\d+ active compound/.test(l));
    for (const line of limitLines) {
      expect(line, `"${line}" still references old limit 5`).not.toMatch(/\b5\b/);
    }
  });
});
