namespace BioStack.Domain.Entities.Graph;

/// <summary>
/// A materialized snapshot of the reviewed compound graph produced by the offline
/// <c>CompoundGraphBuilder</c> (Lane C, step 1).
///
/// One artifact is the unit of provenance: every persisted relationship and finding points back
/// to the artifact that produced it, so a runtime receipt can cite a stable
/// <see cref="ArtifactHash"/> ("this answer used this reviewed graph"). Exactly one artifact is
/// marked <see cref="IsActive"/> at a time; runtime reads always go through the active artifact.
///
/// This is intentionally a pragmatic materialization table, not a normalized graph schema —
/// Lane B will later normalize relationships into <c>Substance</c>/<c>RelationshipEdge</c>/
/// <c>EvidenceClaim</c> without discarding this work.
/// </summary>
public sealed class CompoundGraphArtifact
{
    public Guid Id { get; set; }

    /// <summary>Stable content hash identifying this graph build (the receipt-citable id).</summary>
    public string ArtifactHash { get; set; } = string.Empty;

    /// <summary>Version of the builder that produced the graph (e.g. <c>1.0.0</c>).</summary>
    public string BuilderVersion { get; set; } = string.Empty;

    /// <summary>When the graph was generated by the offline worker (UTC).</summary>
    public DateTime GeneratedAtUtc { get; set; }

    /// <summary>Hash of the upstream source/promotion manifest, when available.</summary>
    public string? SourceManifestHash { get; set; }

    /// <summary>Review/governance state of the artifact (e.g. <c>reviewed</c>, <c>provisional</c>).</summary>
    public string ReviewState { get; set; } = "provisional";

    public int RelationshipCount { get; set; }
    public int FindingCount { get; set; }

    /// <summary>Free-form provenance/metadata (counts, builder inputs) as JSON.</summary>
    public string MetadataJson { get; set; } = "{}";

    /// <summary>Whether this artifact is the one runtime reads from. Only one is active at a time.</summary>
    public bool IsActive { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public ICollection<CompoundGraphRelationship> Relationships { get; set; } = new List<CompoundGraphRelationship>();
    public ICollection<CompoundGraphFinding> Findings { get; set; } = new List<CompoundGraphFinding>();
}
